import express from 'express';
import http from 'http';
import path from 'path';
import { fileURLToPath } from 'url';
import { WebSocketServer, WebSocket } from 'ws';
import { GoogleGenAI, LiveServerMessage, Modality } from '@google/genai';
import dotenv from 'dotenv';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const server = http.createServer(app);
const port = process.env.PORT || 3000;

app.use(express.json());

// Server-side initialization of GoogleGenAI SDK
const apiKey = process.env.GEMINI_API_KEY || '';
const ai = new GoogleGenAI({
  apiKey: apiKey,
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    },
  },
});

// Health & Status endpoint
app.get('/api/voice/status', (req, res) => {
  res.json({
    status: 'online',
    model: 'gemini-3.8-live',
    hasApiKey: Boolean(apiKey && apiKey.length > 5),
    voices: ['Zephyr', 'Puck', 'Charon', 'Kore', 'Fenrir'],
    sampleRateIn: 16000,
    sampleRateOut: 24000,
  });
});

// Fallback TTS endpoint using gemini-3.8-flash-lite-tts
app.post('/api/voice/speak', async (req, res) => {
  try {
    const { text, voice = 'Zephyr', language = 'fr' } = req.body;
    if (!text) {
      return res.status(400).json({ error: 'Text prompt required' });
    }

    let speechStyle = 'Clear, articulate, natural conversational French assistant';
    if (language === 'wo') {
      speechStyle = 'Clear, articulate, natural conversational Wolof (Làmmiñu Wolof) assistant from Senegal';
    } else if (language === 'en') {
      speechStyle = 'Clear, articulate, natural conversational professional English assistant';
    } else if (language === 'es') {
      speechStyle = 'Clear, articulate, natural conversational Spanish (Español) assistant';
    } else if (language === 'ar') {
      speechStyle = 'Clear, articulate, natural conversational Modern Standard Arabic (العربية الفصحى) assistant';
    }

    const response = await ai.models.generateContent({
      model: 'gemini-3.8-flash-lite-tts',
      contents: [
        {
          role: 'user',
          parts: [
            {
              text,
              speechMetadata: {
                style: speechStyle,
              },
            },
          ],
        },
      ],
      config: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: { voiceName: voice },
          },
        },
      },
    });

    const audioBase64 = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
    if (!audioBase64) {
      return res.status(500).json({ error: 'No audio generated by model' });
    }

    res.json({ audio: audioBase64, sampleRate: 24000 });
  } catch (error: any) {
    console.error('TTS error:', error);
    res.status(500).json({ error: error.message || 'Error generating speech' });
  }
});

// WebSocket Server for Gemini Live API (gemini-3.8-live)
const wss = new WebSocketServer({ noServer: true });

server.on('upgrade', (request, socket, head) => {
  const pathname = request.url ? new URL(request.url, `http://${request.headers.host}`).pathname : '';
  if (pathname === '/live' || pathname === '/api/live') {
    wss.handleUpgrade(request, socket, head, (ws) => {
      wss.emit('connection', ws, request);
    });
  }
});

wss.on('connection', async (clientWs: WebSocket) => {
  console.log('Client connected to NEXOMIA Live Voice WebSocket');
  let session: any = null;

  try {
    session = await ai.live.connect({
      model: 'gemini-3.8-live',
      config: {
        responseModalities: [Modality.AUDIO],
        speechConfig: {
          voiceConfig: { prebuiltVoiceConfig: { voiceName: 'Zephyr' } },
        },
        systemInstruction: `Tu es NEXOMIA, l'assistant vocal intelligent unifié de la plateforme d'IA Transversale et Multisectorielle (fusion stratégique NEXORA & OMNIA).
Tu es parfaitement multilingue : FRANÇAIS, WOLOF (Làmmiñu Wolof), ANGLAIS (English), ESPAGNOL (Español) et ARABE (العربية).
- Si l'usager te parle en Wolof, réponds-lui naturellement, poliment et avec fluidité en Wolof.
- Si l'usager te parle en Français, réponds-lui en Français.
- Si l'usager te parle en Anglais, réponds-lui en Anglais (English).
- Si l'usager te parle en Espagnol, réponds-lui en Espagnol (Español).
- Si l'usager te parle en Arabe, réponds-lui en Arabe (العربية الفصحى).
- Tu as une maîtrise complète des 13 secteurs (Commerce, Finance, Santé, Industrie, Énergie, Transport, etc.), de la détection de fraude bancaire (p. ex. 640 € à Singapour), de la gestion omnicanale des stocks et de l'autonomie graduée (Niveau 1, Niveau 2, Niveau 3).
- Tes réponses orales doivent être concises (1 à 3 phrases claires et percutantes), dynamiques et chaleureuses.`,
      },
      callbacks: {
        onmessage: (message: LiveServerMessage) => {
          if (!clientWs || clientWs.readyState !== WebSocket.OPEN) return;

          const parts = message.serverContent?.modelTurn?.parts;
          if (parts && parts.length > 0) {
            for (const part of parts) {
              if (part.inlineData?.data) {
                clientWs.send(JSON.stringify({ 
                  type: 'audio',
                  audio: part.inlineData.data 
                }));
              }
              if (part.text) {
                clientWs.send(JSON.stringify({ 
                  type: 'transcript',
                  text: part.text 
                }));
              }
            }
          }

          if (message.serverContent?.interrupted) {
            clientWs.send(JSON.stringify({ 
              type: 'interrupted',
              interrupted: true 
            }));
          }
        },
      },
    });

    clientWs.send(JSON.stringify({ 
      type: 'status', 
      status: 'connected', 
      model: 'gemini-3.8-live',
      message: 'Session vocale temps réel gemini-3.8-live établie' 
    }));

    clientWs.on('message', (data: Buffer | string) => {
      try {
        const payload = JSON.parse(data.toString());

        if (payload.audio && session) {
          session.sendRealtimeInput({
            audio: { data: payload.audio, mimeType: 'audio/pcm;rate=16000' },
          });
        } else if (payload.text && session) {
          session.sendRealtimeInput({
            text: payload.text,
          });
        }
      } catch (err) {
        console.error('Error handling client message:', err);
      }
    });

    clientWs.on('close', () => {
      console.log('Client disconnected from Live Voice');
      if (session) {
        try {
          session.close();
        } catch {}
      }
    });

    clientWs.on('error', (err) => {
      console.error('WebSocket client error:', err);
      if (session) {
        try {
          session.close();
        } catch {}
      }
    });

  } catch (err: any) {
    console.error('Failed to connect to Gemini Live API:', err);
    if (clientWs.readyState === WebSocket.OPEN) {
      clientWs.send(JSON.stringify({
        type: 'error',
        error: err.message || 'Impossible de se connecter à gemini-3.8-live',
      }));
    }
  }
});

// Mount Vite in development or serve static in production
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const { createServer: createViteServer } = await import('vite');
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static(path.resolve(__dirname, 'dist')));
    app.get('*', (req, res) => {
      res.sendFile(path.resolve(__dirname, 'dist', 'index.html'));
    });
  }

  server.listen(port, () => {
    console.log(`NEXOMIA Server running on http://localhost:${port} with Gemini Live API support`);
  });
}

startServer();
